# Generated by Django 4.1 on 2022-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform',
            name='start_date',
            field=models.DateTimeField(default=0),
        ),
    ]
