# Generated by Django 4.1 on 2022-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRP', '0003_alter_inform_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform',
            name='files',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
